-- ============================================================
-- SUPABASE SQL SCHEMA — CV RAZKA PRATAMA MANDIRI
-- ============================================================
-- Cara menggunakan:
-- 1. Buka https://supabase.com → Dashboard → SQL Editor
-- 2. Klik "New Query"
-- 3. Paste seluruh script ini
-- 4. Klik "Run" untuk membuat tabel-tabel
-- 5. Buka Authentication → Providers → pastikan Email/Password aktif
-- 6. Buka Authentication → Users → tambah admin user
-- ============================================================

-- ===== 1. SERVICES TABLE =====
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL DEFAULT 'wrench',
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 2. PORTFOLIO TABLE =====
CREATE TABLE IF NOT EXISTS portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'residensial',
  location TEXT,
  description TEXT,
  image_url TEXT,
  year TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 3. TESTIMONIALS TABLE =====
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  position TEXT,
  quote TEXT NOT NULL,
  avatar_url TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 4. ARTICLES TABLE =====
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  date DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'draft',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 5. SETTINGS TABLE =====
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO settings (key, value) VALUES
('company', '{
  "name": "CV RAZKA PRATAMA MANDIRI",
  "short": "RAZKA PRATAMA",
  "address": "Dusun Songgorejo, Ds. Songgon, Kec. Songgon, Kab. Banyuwangi, Jawa Timur 68463",
  "whatsapp": "082234613934",
  "email": "pratamamandiri945@gmail.com",
  "hours": "Senin – Sabtu: 08:00 – 17:00 WIB",
  "year": "2016"
}'::jsonb),
('hero', '{
  "bg_url": "https://images.unsplash.com/photo-1541888946425-d81bb52b7f7b?w=1600&q=85",
  "title": "Kontraktor Bangunan & Infrastruktur Terpercaya",
  "subtitle": "Banyuwangi & Jawa Timur",
  "description": "Mewujudkan konstruksi solid, presisi, dan tepat waktu untuk proyek pemerintah dan bangunan umum.",
  "badge": "Kontraktor Pemerintah & Konstruksi Umum",
  "cta": "Konsultasi Proyek",
  "overlay_opacity": 0.88
}'::jsonb),
('seo', '{
  "title": "CV RAZKA PRATAMA MANDIRI – Kontraktor Bangunan & Infrastruktur Pemerintah Banyuwangi",
  "description": "CV RAZKA PRATAMA MANDIRI – Kontraktor bangunan terpercaya di Banyuwangi, spesialis infrastruktur pemerintah, pekerjaan sipil, renovasi, dan desain arsitektur.",
  "keywords": "kontraktor pemerintah Banyuwangi, jasa bangunan, pekerjaan sipil, infrastruktur",
  "og_image": "https://images.unsplash.com/photo-1541888946425-d81bb52b7f7b?w=1200&q=80"
}'::jsonb),
('overlay', '{
  "bg_url": "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1600&q=80",
  "title": "Bidang Keahlian Kami",
  "description": "Berpengalaman dalam berbagai jenis proyek konstruksi, dari infrastruktur pemerintah hingga bangunan residensial.",
  "color": "#080e1a",
  "opacity": 0.6
}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- ===== 6. ENABLE ROW LEVEL SECURITY =====
-- Untuk keamanan, aktifkan RLS di semua tabel
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- ===== 7. CREATE POLICIES =====
-- Hanya user terautentikasi yang bisa baca/tulis data
CREATE POLICY "Allow authenticated users full access to services"
  ON services FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to portfolio"
  ON portfolio FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to testimonials"
  ON testimonials FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to articles"
  ON articles FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to settings"
  ON settings FOR ALL USING (auth.role() = 'authenticated');

-- Public read access (untuk website utama)
CREATE POLICY "Allow public read access to services"
  ON services FOR SELECT USING (true);

CREATE POLICY "Allow public read access to portfolio"
  ON portfolio FOR SELECT USING (true);

CREATE POLICY "Allow public read access to testimonials"
  ON testimonials FOR SELECT USING (true);

CREATE POLICY "Allow public read access to articles"
  ON articles FOR SELECT USING (true);

CREATE POLICY "Allow public read access to settings"
  ON settings FOR SELECT USING (true);

-- ============================================================
-- SELESAI. Tabel siap digunakan oleh admin panel.
-- ============================================================
