-- ============================================================
-- SUPABASE SQL SCHEMA — CV RAZKA PRATAMA MANDIRI
-- ============================================================
-- Cara menggunakan:
-- 1. Buka https://supabase.com → Dashboard → SQL Editor
-- 2. Klik "New Query"
-- 3. Paste seluruh script ini
-- 4. Klik "Run" untuk membuat tabel-tabel
-- 5. Buka Authentication → Providers → pastikan Email/Password aktif
-- 6. Buka Authentication → Users → tambah admin user
-- ============================================================

-- ===== 1. SERVICES TABLE =====
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL DEFAULT 'wrench',
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 2. PORTFOLIO TABLE =====
CREATE TABLE IF NOT EXISTS portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'residensial',
  location TEXT,
  description TEXT,
  image_url TEXT,
  year TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 3. TESTIMONIALS TABLE =====
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  position TEXT,
  quote TEXT NOT NULL,
  avatar_url TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 4. ARTICLES TABLE =====
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  date DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'draft',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 5. SETTINGS TABLE =====
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO settings (key, value) VALUES
('company', '{
  "name": "CV RAZKA PRATAMA MANDIRI",
  "short": "RAZKA PRATAMA",
  "address": "Dusun Songgorejo, Ds. Songgon, Kec. Songgon, Kab. Banyuwangi, Jawa Timur 68463",
  "whatsapp": "082234613934",
  "email": "pratamamandiri945@gmail.com",
  "hours": "Senin – Sabtu: 08:00 – 17:00 WIB",
  "year": "2016",
  "facebook": "https://www.facebook.com/share/184uWS9FLW/",
  "instagram": "https://www.instagram.com/rpm0026"
}'::jsonb),
('hero', '{
  "bg_url": "https://images.unsplash.com/photo-1541888946425-d81bb52b7f7b?w=1600&q=85",
  "title": "Kontraktor Bangunan & Infrastruktur Terpercaya",
  "subtitle": "Banyuwangi & Jawa Timur",
  "description": "Mewujudkan konstruksi solid, presisi, dan tepat waktu untuk proyek pemerintah dan bangunan umum.",
  "badge": "Kontraktor Pemerintah & Konstruksi Umum",
  "cta": "Konsultasi Proyek",
  "overlay_opacity": 0.88
}'::jsonb),
('seo', '{
  "title": "CV RAZKA PRATAMA MANDIRI – Kontraktor Bangunan & Infrastruktur Pemerintah Banyuwangi",
  "description": "CV RAZKA PRATAMA MANDIRI – Kontraktor bangunan terpercaya di Banyuwangi, spesialis infrastruktur pemerintah, pekerjaan sipil, renovasi, dan desain arsitektur.",
  "keywords": "kontraktor pemerintah Banyuwangi, jasa bangunan, pekerjaan sipil, infrastruktur",
  "og_image": "https://images.unsplash.com/photo-1541888946425-d81bb52b7f7b?w=1200&q=80"
}'::jsonb),
('overlay', '{
  "bg_url": "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1600&q=80",
  "title": "Bidang Keahlian Kami",
  "description": "Berpengalaman dalam berbagai jenis proyek konstruksi, dari infrastruktur pemerintah hingga bangunan residensial.",
  "color": "#080e1a",
  "opacity": 0.6
}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- ===== 6. ENABLE ROW LEVEL SECURITY =====
-- Untuk keamanan, aktifkan RLS di semua tabel
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- ===== 7. DROP EXISTING POLICIES (idempotent) =====
DROP POLICY IF EXISTS "Allow authenticated users full access to services" ON services;
DROP POLICY IF EXISTS "Allow authenticated users full access to portfolio" ON portfolio;
DROP POLICY IF EXISTS "Allow authenticated users full access to testimonials" ON testimonials;
DROP POLICY IF EXISTS "Allow authenticated users full access to articles" ON articles;
DROP POLICY IF EXISTS "Allow authenticated users full access to settings" ON settings;
DROP POLICY IF EXISTS "Allow public read access to services" ON services;
DROP POLICY IF EXISTS "Allow public read access to portfolio" ON portfolio;
DROP POLICY IF EXISTS "Allow public read access to testimonials" ON testimonials;
DROP POLICY IF EXISTS "Allow public read access to articles" ON articles;
DROP POLICY IF EXISTS "Allow public read access to settings" ON settings;

-- ===== 8. CREATE POLICIES =====
-- Hanya user terautentikasi yang bisa baca/tulis data
CREATE POLICY "Allow authenticated users full access to services"
  ON services FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to portfolio"
  ON portfolio FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to testimonials"
  ON testimonials FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to articles"
  ON articles FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users full access to settings"
  ON settings FOR ALL USING (auth.role() = 'authenticated');

-- Public read access (untuk website utama)
CREATE POLICY "Allow public read access to services"
  ON services FOR SELECT USING (true);

CREATE POLICY "Allow public read access to portfolio"
  ON portfolio FOR SELECT USING (true);

CREATE POLICY "Allow public read access to testimonials"
  ON testimonials FOR SELECT USING (true);

CREATE POLICY "Allow public read access to articles"
  ON articles FOR SELECT USING (true);

CREATE POLICY "Allow public read access to settings"
  ON settings FOR SELECT USING (true);

-- ===== 9. STORAGE BUCKET (untuk upload gambar) =====
-- Buat bucket storage untuk image upload
-- Cara alternatif: Buka Supabase Dashboard → Storage → Create bucket "razka-images" (public)
INSERT INTO storage.buckets (id, name, public, avif_autodetection)
VALUES ('razka-images', 'razka-images', true, false)
ON CONFLICT (id) DO NOTHING;

-- Policy: authenticated users can upload/delete
DROP POLICY IF EXISTS "Allow authenticated upload" ON storage.objects;
CREATE POLICY "Allow authenticated upload"
  ON storage.objects FOR INSERT WITH CHECK (
    bucket_id = 'razka-images' AND auth.role() = 'authenticated'
  );

DROP POLICY IF EXISTS "Allow authenticated delete" ON storage.objects;
CREATE POLICY "Allow authenticated delete"
  ON storage.objects FOR DELETE USING (
    bucket_id = 'razka-images' AND auth.role() = 'authenticated'
  );

DROP POLICY IF EXISTS "Allow public read" ON storage.objects;
CREATE POLICY "Allow public read"
  ON storage.objects FOR SELECT USING (
    bucket_id = 'razka-images'
  );

-- ===== 10. PRACTICE AREAS TABLE =====
CREATE TABLE IF NOT EXISTS practice_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon TEXT NOT NULL DEFAULT 'landmark',
  title TEXT NOT NULL,
  description TEXT,
  tag TEXT DEFAULT 'Keahlian',
  tag_color TEXT DEFAULT '#e63946',
  icon_color TEXT DEFAULT '#e63946',
  image_url TEXT,
  features JSONB DEFAULT '[]',
  stats JSONB DEFAULT '[]',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 11. CLIENTS TABLE =====
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon_class TEXT DEFAULT 'fas fa-building',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 12. HOTSPOTS TABLE =====
CREATE TABLE IF NOT EXISTS hotspots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT DEFAULT 'fas fa-plus',
  position_top INTEGER DEFAULT 25,
  position_left INTEGER DEFAULT 30,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE practice_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE hotspots ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Allow authenticated users full access to practice_areas" ON practice_areas;
DROP POLICY IF EXISTS "Allow authenticated users full access to clients" ON clients;
DROP POLICY IF EXISTS "Allow authenticated users full access to hotspots" ON hotspots;
DROP POLICY IF EXISTS "Allow public read access to practice_areas" ON practice_areas;
DROP POLICY IF EXISTS "Allow public read access to clients" ON clients;
DROP POLICY IF EXISTS "Allow public read access to hotspots" ON hotspots;

-- Create policies
CREATE POLICY "Allow authenticated users full access to practice_areas"
  ON practice_areas FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users full access to clients"
  ON clients FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users full access to hotspots"
  ON hotspots FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow public read access to practice_areas"
  ON practice_areas FOR SELECT USING (true);
CREATE POLICY "Allow public read access to clients"
  ON clients FOR SELECT USING (true);
CREATE POLICY "Allow public read access to hotspots"
  ON hotspots FOR SELECT USING (true);

-- Insert default practice areas
INSERT INTO practice_areas (icon, title, description, tag, tag_color, icon_color, image_url, features, stats, sort_order)
VALUES
('landmark', 'Infrastruktur Pemerintah', 'Proyek pembangunan dan pemeliharaan infrastruktur publik seperti jalan, jembatan, irigasi, drainase, dan fasilitas umum lainnya.', 'Proyek Pemerintah', '#e63946', '#e63946', 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&q=80', '["Pembangunan jalan & jembatan", "Sistem drainase & irigasi", "Bangunan pemerintahan", "Infrastruktur pedesaan"]', '[{"label":"Proyek","value":"25+"},{"label":"Kepuasan","value":"98%"},{"label":"Tepat Waktu","value":"100%"}]', 0),
('building', 'Konstruksi Umum', 'Pekerjaan konstruksi menyeluruh untuk bangunan komersial, perkantoran, gudang, dan fasilitas umum dengan standar kualitas tinggi.', 'Konstruksi', '#f59e0b', '#f59e0b', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&q=80', '["Bangunan komersial", "Gedung perkantoran", "Fasilitas umum", "Gudang & pabrik"]', '[{"label":"Proyek","value":"40+"},{"label":"Kepuasan","value":"95%"},{"label":"Garansi","value":"5 Thn"}]', 1),
('store', 'Proyek Komersial', 'Renovasi dan pembangunan ruang usaha, ruko, pertokoan, dan fasilitas komersial dengan desain fungsional dan estetis.', 'Komersial', '#3b82f6', '#3b82f6', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80', '["Ruko & pertokoan", "Renovasi ruang usaha", "Interior komersial", "Fasad bangunan"]', '[{"label":"Proyek","value":"15+"},{"label":"Kepuasan","value":"96%"},{"label":"Tepat Waktu","value":"98%"}]', 2),
('home', 'Proyek Residensial', 'Pembangunan dan renovasi rumah tinggal, perumahan, dan hunian pribadi dengan sentuhan arsitektur modern dan tradisional.', 'Residensial', '#10b981', '#10b981', 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80', '["Rumah tinggal", "Perumahan", "Renovasi hunian", "Desain interior"]', '[{"label":"Proyek","value":"30+"},{"label":"Kepuasan","value":"97%"},{"label":"Garansi","value":"5 Thn"}]', 3)
ON CONFLICT DO NOTHING;

-- Insert default clients
INSERT INTO clients (name, icon_class, sort_order)
VALUES
('Pemerintah Kab. Banyuwangi', 'fas fa-landmark', 0),
('Dinas PUPR Banyuwangi', 'fas fa-university', 1),
('Kecamatan Songgon', 'fas fa-city', 2),
('Dinas Pendidikan Banyuwangi', 'fas fa-school', 3),
('PT. Bumi Sejahtera', 'fas fa-store', 4),
('CV. Karya Bersama', 'fas fa-building', 5)
ON CONFLICT DO NOTHING;

-- Insert default hotspots
INSERT INTO hotspots (title, description, icon, position_top, position_left, sort_order)
VALUES
('Gedung Pemerintahan', 'Pembangunan kantor kecamatan dan balai desa di Banyuwangi.', 'fas fa-plus', 25, 30, 0),
('Jalan & Drainase', 'Proyek infrastruktur jalan lingkungan dan drainase terintegrasi.', 'fas fa-plus', 55, 55, 1),
('Konstruksi Beton', 'Pekerjaan struktur beton untuk fondasi gedung komersial.', 'fas fa-plus', 70, 20, 2)
ON CONFLICT DO NOTHING;

-- Insert default marquee + beforeafter settings
INSERT INTO settings (key, value) VALUES
('marquee', '["🏗️ Proyek Infrastruktur Pemerintah", "🏢 Konstruksi Komersial & Perkantoran", "🏠 Bangunan Residensial & Perumahan", "📍 Banyuwangi & Jawa Timur", "✅ Tepat Waktu & Berkualitas"]'::jsonb),
('beforeafter', '{
  "before_url": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
  "after_url": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
  "label_before": "Sebelum",
  "label_after": "Sesudah"
}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- SELESAI. Tabel siap digunakan oleh admin panel.
-- ============================================================
